name: Deploy package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: lein deps
      - name: Lint
        run: lein lint
      - name: Run tests
        run: lein test
      - name: Deploy to clojars
        run: CLOJARS_USERNAME=${{ secrets.CLOJARS_USERNAME }} CLOJARS_PASSWORD=${{ secrets.CLOJARS_PASSWORD }} lein deploy clojars
